### ISSUE TITLE
How to start using

### ISSUE THREAD

**Issue by r2n2** [melioratus/org-mode#17]
New Atom user with a long EMACS and org-mode history.   I can use org-mode; however, need a bit of a hint on how to activate (and use?) org-mode in Atom.   I've opened existing org files and don't see any obvious way to even get org-mode in Atom to fold a tree.

A Quick Start Guide, nothing too sophisticated, just for using org-mode in Atom sure would be helpful.

**Comment by melioratus** [comment]
If you open a text file with the `.org` file extension the syntax coloring should change automatically. If it doesn't try uninstalling org-mode and reinstalling it with using the Atom build-in package manager.

At the moment, all that org-mode in atom does is syntax highlighting.

e.g. 

The link

`[[https://www.google.com][Google]]`

should be display like

`Google`


As a workaround, try out the [orgfld](https://atom.io/packages/orgfld) package, which will do folding but not using the tab like emacs. 

In my spare time I've been trying to implement code that would fold trees and blocks, etc... like emacs does because it would really help with navigating long outlines.

Unfortunately, I haven't been learned how to out implement any similar features inside the package yet.

My goal is to eventually match all the org-mode functionality in emacs but that lofty goal is a long ways off at the moment.

Thanks for your patience!

~ Melioratus

**Comment by dowenk** [comment]
Thank you for providing this package and working to flesh out the features.    I use emacs+org-mode to organize my entire life.   I would love to see the same functionally in atom (especially tab expansion as well as indent).  I will continue to use org-mode and orgfld.   Eventually I would like to learn to extend atom an perhaps contribute.  Thanks again.
